package com.regionaltrade.view;

import java.awt.BorderLayout;


/**
 *
 * @author Cristian
 */

public class MainWindow extends javax.swing.JFrame {

    /**
     * Creates new form MainWindow
     * 
     */
    public MainWindow() {
    
        initComponents(); 
        
        jSplitPane1.setDividerLocation(500);
        setLocationRelativeTo(null);
        setTitle("PreventSoft");
       
         this.setResizable(false);

        //setExtendedState(javax.swing.JFrame.MAXIMIZED_BOTH);


        
    }

    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jSplitPane1 = new javax.swing.JSplitPane();
        jScrollPaneRegistrationForm = new javax.swing.JScrollPane();
        registrationForm1 = new com.regionaltrade.view.RegistrationForm();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableMachine1 = new com.regionaltrade.view.TableMachine();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.FlowLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jSplitPane1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(51, 51, 255)));
        jSplitPane1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jSplitPane1.setDoubleBuffered(true);

        jScrollPaneRegistrationForm.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jScrollPaneRegistrationForm.setViewportView(registrationForm1);

        jSplitPane1.setRightComponent(jScrollPaneRegistrationForm);

        jScrollPane2.setViewportView(tableMachine1);

        jSplitPane1.setLeftComponent(jScrollPane2);

        jPanel1.add(jSplitPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 920, 560));

        getContentPane().add(jPanel1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPaneRegistrationForm;
    private javax.swing.JSplitPane jSplitPane1;
    private com.regionaltrade.view.RegistrationForm registrationForm1;
    private com.regionaltrade.view.TableMachine tableMachine1;
    // End of variables declaration//GEN-END:variables
}
